server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_platform?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ding.demo.auth.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT Configuration
app:
  jwt:
    # This should be a secure random string, at least 32 characters long
    secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c6b1d4f7e2a5
    # 24 hours in milliseconds
    expiration: 86400000

# Logging Configuration
logging:
  level:
    root: INFO
    com.ding.demo.auth: DEBUG
    org.springframework.security: DEBUG
